[workspace]
resolver = "2"

members = [
  "crates/rg_main",
  "crates/rg_pixel_material",
  "crates/rg_terrain",
  "crates/rg_billboard",
  "crates/rg_ai",
]

[workspace.dependencies]
bevy = { version = "0.11.0-dev", features = ["dynamic_linking", "trace_tracy"] }
bevy_rapier3d = "0.21"
bytemuck = "1.7"
futures-lite = "1.13"
turborand = "0.10"

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy" }
nalgebra = { git = "https://github.com/Dig-Doug/nalgebra", branch = "glam-024" }
bevy_rapier3d = { git = "https://github.com/devil-ira/bevy_rapier", branch = "bevy-0.11" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
