[workspace]
resolver = "2"

members = [
  "crates/rg_main",
  "crates/rg_pixel_material",
  "crates/rg_terrain",
  "crates/rg_billboard",
]

[workspace.dependencies]
futures-lite = "1.13"
bytemuck = "1.7"

[workspace.dependencies.bevy]
git = "https://github.com/bevyengine/bevy.git"
rev = "bb59509d44d2979e4b91bd0f998c047f16b89dd0"
features = ["dynamic_linking", "trace_tracy"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
