[package]
name = "rg_camera_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
rg_core = { path = "../rg_core" }
rg_pixel_material = { path = "../rg_pixel_material" }
rg_terrain = { path = "../rg_terrain" }

bevy = { workspace = true }
