[package]
name = "rg_terrain"
version = "0.1.0"
edition = "2021"

[dependencies]
rg_pixel_material = { path = "../rg_pixel_material" }
rg_billboard = { path = "../rg_billboard" }

bevy = { workspace = true }
futures-lite = { workspace = true }
turborand = { workspace = true }
