[package]
name = "rg_dev_overlay"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy-inspector-egui = { workspace = true }
bevy_egui = { workspace = true }
bevy_xpbd_3d = { workspace = true }
