[package]
name = "rg_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_rapier3d = { workspace = true }
bitflags = { workspace = true }
parking_lot = { workspace = true }
rand = "0.8"
rand_pcg = "0.3"
