[package]
name = "rg_grid"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bytemuck = { workspace = true }
image = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
zstd = { workspace = true }
